data_dir: ./data/C4-50B/
output: ./output
seed: 42
log_interval: 10
save_freq: 9999999999

orthogonal_type: all
hidden_size: 1280
num_layers: 24
num_heads: 16
mlp_ratio: 3
max_position_embeddings: 2048
vocab_size: 32000
rope_theta: 10000.0
rms_norm_eps: 1e-6
attention_dropout: 0.0
tie_word_embeddings: True

batch_size: 8
global_batch_size: 512
seq_length: 2048
num_steps: 21000
lr: 1.2e-3
min_lr: 1.2e-4
weight_decay: 0.1
clip_grad: 1.0

muon_lr: 1.0e-3
muon_min_lr: 1.0e-4
muon_momentum: 0.95
muon_weight_decay: 0.1
muon_nesterov: true
muon_ns_steps: 5
muon_eps: 1e-7
ortho_update: False
transpose_o: False
