extends: ../../base/adamw_360m_4096l.yaml
train:
  output: ./output/360m_4096l/sweeps/adamw_lr_wd_cosine_power/adamw_lr0p0006_wd0p1_cos1
  lr: 0.0006
  min_lr: 6.0e-05
  weight_decay: 0.1
  cosine_power: 1.0
